language: objective-c
os: osx
osx_image: xcode9.3
before_install:
  - export PATH=$PATH:$JAVA_HOME/bin
  - nvm install 6
before_script:
  - npm install -g appium
  - npm install -g appium-doctor
  - appium-doctor
  - appium &
script:
  - xcrun simctl list
  - mvn clean test
